### ISSUE TITLE
隧道已连接，但是远程桌面连接不上

### ISSUE THREAD

**Issue by hudada-stack** [zgxkbtl/Alley#2]
如题，抓包显示ip，端口信息啥的都没问题，控制台信息也都正常输出，但是远程桌面的时候一直显示在远程桌面配置中，楼主知道这是啥情况么

**Comment by zgxkbtl** [comment]
配置中应该是已经通了，可能是你的mstsc设置有问题，你可以尝试局域网连一下。

要验证有没有通，可以本地起一个服务器试试。

```python
python -m http.server 
```

然后把8000端口配上你的服务器，看看反代能不能进来。
